### ISSUE TITLE
Cloned, NPM Install, Grunt build issues "Variable 'require' must by of type 'Require' but is 'NodeRequire'

### ISSUE THREAD

**Issue by AcousticGuitar** [cschleiden/vsts-extension-ts-seed-simple#15]
I cloned this lib, ran NPM Install and performed a Grunt Build...

![image](https://cloud.githubusercontent.com/assets/10676026/26166556/731cb192-3af9-11e7-9211-3a64ebe6651d.png)

Grunt Build errors here.
Using tsc v2.3.2
../../../../node_modules/@types/node/index.d.ts(73,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'Require', but here has type 'NodeRequire'.

**Comment by cschleiden** [comment]
Thanks for reporting, this should be fixed now (and yes, I know, a bit late :))
